# Generated by Django 3.1 on 2023-08-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='middletask',
            name='delivery',
            field=models.DateField(null=True, verbose_name='納期'),
        ),
    ]
