# Generated by Django 3.1 on 2023-08-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20230826_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottomtask',
            old_name='status',
            new_name='completed',
        ),
    ]
